using System;
using Herramienta.Modelos.Interfaces;

namespace Herramienta.Modelos.Entidades
{
	public class Declaracion:IEntidad, IConFechaRadicacion
    {
        public int Id { get; set; }
        public DateTime? Fecha_Radicacion { get; set; }
        public DateTime? Fecha_Declaracion { get; set; }
        public string Numero_Declaracion { get; set; }
        public DateTime? Fecha_Desplazamiento { get; set; }
        public DateTime? Fecha_Valoracion { get; set; }
        public int? Gestantes { get; set; }
        public int? Menores_Ninos { get; set; }
        public int? Menores_Ninas { get; set; }
        public int? Recien_Nacidos { get; set; }
        public int? Lactantes { get; set; }
        public int? Resto_Nucleo { get; set; }
        public int? Id_Fuente { get; set; }
        public int? Id_Municipio_Expulsor { get; set; }
        public int? Id_Ha_Regresado { get; set; }
        public int? Id_Retornaria { get; set; }
        public int? Id_Explicacion_Retorno { get; set; }
        public int? Id_Ha_Declarado_Antes { get; set; }
        public int? Id_Ha_Recibido_Ayuda { get; set; }
        public int? Id_Ha_Muerto_Alguien { get; set; }
        public int? Cuantos_Muertos { get; set; }
        public int? Cuantos_Muertos_Menores { get; set; }
        public int? Id_Motivo_Muerte { get; set; }
        public int? Id_Parentesco_Muerte { get; set; }
        public int? Id_Enfermedad { get; set; }
        public int? Id_Velar_Enterrar { get; set; }
        public int? Id_Tiene_Desaparecido { get; set; }
        public int? Id_Parentesco_Desaparecido { get; set; }
        public int? Id_Reporto { get; set; }
        public int? Id_Entidad_Legal { get; set; }
        public int? Id_Aplico_Reparaciones { get; set; }
        public int? Dias_Aplico { get; set; }
        public int? Id_Estado_Aplicacion { get; set; }
        public int? Id_Motivo_No_Aplico { get; set; }
        public int? Id_Llegada_Insultos { get; set; }
        public int? Id_Llegada_Insultos_Usted { get; set; }
        public int? Id_Llegada_Insultos_Miembro { get; set; }
        public string Llegada_Insultos_Agresor { get; set; }
        public int? Id_Llegada_Sexual { get; set; }
        public int? Id_Llegada_Sexual_Usted { get; set; }
        public int? Id_Llegada_Sexual_Miembro { get; set; }
        public string Llegada_Sexual_Agresor { get; set; }
        public int? Id_Llegada_Golpes { get; set; }
        public int? Id_Llegada_Golpes_Usted { get; set; }
        public int? Id_Llegada_Golpes_Miembro { get; set; }
        public string Llegada_Golpes_Agresor { get; set; }
        public DateTime? Fecha_Segunda_Encuesta { get; set; }
        public int? Id_Ha_Redibido_Ayuda_Despues { get; set; }
        public int? Dias_Aplico_Despues { get; set; }
        public int? Id_Estatus_Aplicacion_Despues { get; set; }
        public int? Id_Razon_No_Aplico { get; set; }
        public int? Id_Oido_Mesa_Desplazados { get; set; }
        public int? Id_Pertenece_Asociacion { get; set; }
        public string Cual_Asociacion { get; set; }
        public int? Id_Esta_Trabajando { get; set; }
        public int? Id_beneficiado_programas { get; set; }
        public int? Id_Grupo { get; set; }
        public int? Id_Regional { get; set; }
        public int? Id_Atender { get; set; }
        public int? Id_Motivo_Noatender { get; set; }
        public int? Id_Tipo_Tenencia_Vivienda { get; set; }
        public int? Id_Cuantas_Habitaciones { get; set; }
        public int? Id_Cuantas_Personas_Vivienda { get; set; }
        public int? Id_Cuantas_Personas_Habitacion { get; set; }
        public int? Id_Materiales_Vivienda { get; set; }
        public int? Id_Forma_Declaracion { get; set; }
        public int? Id_Departamento_Expulsor { get; set; }
        public int? Id_Cuantos_Desplazamientos { get; set; }
        public string Lugar_Desplazamiento { get; set; }
        public DateTime? Fecha_Desplazamiento_Anterior { get; set; }
        public int? Id_Motivo_Desplazamiento { get; set; }
        public int? Id_Cuanto_Tiempo_Demoro { get; set; }
        public int? Id_Motivo_Demora { get; set; }
        public int? Id_Motivo_NoDeclaro_Municipio { get; set; }
        public int? Id_Vivio_Cabezera_Municipal { get; set; }
        public int? Id_Tiempo_Casco_Urbano { get; set; }
        public int? Id_Entidad_Inicial_Atencion { get; set; }
        public int? Id_Recibio_Ayuda_Entidad_Inicial { get; set; }
        public int? Id_Como_Fue_Atencion { get; set; }
        public int? Id_Como_Brindar_Atencion { get; set; }
        public decimal? Promedio_Ingresos_Mensuales { get; set; }
        public DateTime? Fecha_Muerte { get; set; }
        public int? Cuantos_Familiares_Desaparecidos { get; set; }
        public int? Id_Porque_No_Reporto { get; set; }
        public int? Id_Tipo_Bien_Rural { get; set; }
        public int? Id_Documento_Propiedad { get; set; }
        public int? Id_Destino_Tierra { get; set; }
        public int? Id_Situacion_Actual_Tierras { get; set; }
        public int? Id_Despues_Afiliado_Regimen_Subsidiado { get; set; }
        public int? Cuantos_Despues_Afiliado_Regimen_Subsidiado { get; set; }
        public int? Id_Despues_Afiliado_Regimen_Contributivo { get; set; }
        public int? Cuantos_Despues_Afiliado_Regimen_Contributivo { get; set; }
        public int? Id_Despues_Afiliado_Sisben { get; set; }
        public int? Cuantos_Despues_Afiliado_Sisben { get; set; }
        public int? Id_Despues_Hijos_617 { get; set; }
        public int? Cuantos_Despues_Hijos { get; set; }
        public int? Cuantos_Despues_Hijos_Estudian { get; set; }
        public int? Id_ley_reparacion { get; set; }
        public int? Id_Es_Del_Municipio { get; set; }
        public string Motivo_Desplazamiento { get; set; }
        public DateTime? Fecha_Ingreso_Registro { get; set; }
        public int? Tipo_Declaracion { get; set; }
        public string Horario { get; set; }
        public int? Id_Tipo_Familia_desplazada { get; set; }
        public int? Id_Vulnerables_NoDesplazada { get; set; }
        public string Motivo_Remision { get; set; }
        public int? Id_Concejo_Expulsor { get; set; }
        public int? Id_Solicito_ayuda { get; set; }
        public int? Id_lugar_fuente { get; set; }
        public int? Id_EnLinea { get; set; }
        public int? Id_Agua_Potable { get; set; }
        public int? Id_Tiene_Documento { get; set; }
        public int? Id_Tipo_Familia_No_Desplazada { get; set; }
        public DateTime? Fecha_Creacion { get; set; }
        public int? Id_Usuario_Creacion { get; set; }
        public DateTime? Fecha_Modificacion { get; set; }
        public int? Id_Usuario_Modificacion { get; set; }
        public DateTime? Fecha_Cierre { get; set; }
        public bool? Cierre { get; set; }
        public int? Id_Familias_Accion { get; set; }
        public int? Id_Red_Unidos { get; set; }
        public string Municipio_Unidos { get; set; }
        public int? Id_VBG_general { get; set; }
        public string VBG_General_Agresor { get; set; }
        public int? Id_Ha_Muerto_Despues { get; set; }
        public int? Id_Solicito_Atencion_Psicologica { get; set; }
        public int? Id_Afectado_Desplazamiento { get; set; }
        public int? Id_Emociones { get; set; }
        public string Vereda_Desplazamiento { get; set; }
        public int? Id_Tipo_Adiccion { get; set; }
        public int? Id_Adiccion_Alcohol { get; set; }
        public int? Id_Adiccion_Droga { get; set; }
        public string Observaciones { get; set; }
        public string Municipio_Familias_Accion { get; set; }
        public int? Id_Municipio_Faccion { get; set; }
    }
}
